use LogExpTest
CREATE TABLE WAREHOUSES 
(
		WH_ID INT NOT NULL,
		WH_X INT NOT NULL,
		WH_Y INT NOT NULL,
		PRIMARY KEY(WH_ID)
);
CREATE TABLE WH_GOODS
(
		WH_ID INT NOT NULL,
		GOOD_ID INT NOT NULL,
		AVAILABLE_QUANTITY INT NOT NULL,
		RESERVED_QUANTITY INT NOT NULL,
		PRIMARY KEY(WH_ID,GOOD_ID)
);
CREATE TABLE SHOPS_MANAGERS
(
	WORKER_ID INT PRIMARY KEY,
	SHOP_ID INT
);
CREATE TABLE G_NAMES
(
	GOOD_ID INT PRIMARY KEY NOT NULL,
	GOOD_NAME VARCHAR(50) NOT NULL,
	COST INT NOT NULL
);
CREATE TABLE WORKERS_LAB
(
	ID INT PRIMARY KEY NOT NULL,
	F_NAME VARCHAR(50) NOT NULL,
	SURNAME VARCHAR(50) NOT NULL,
);
CREATE TABLE SHOPS
(
	SHOP_ID INT NOT NULL,  
	SHOP_X INT NOT NULL,
	SHOP_Y INT NOT NULL,
	PRIMARY KEY(SHOP_ID,SHOP_X,SHOP_Y)
);
CREATE TABLE SH_GOODS
(
		SH_ID INT NOT NULL,
		GOOD_ID INT NOT NULL,
		QUANTITY INT NOT NULL,
		PRIMARY KEY(SH_ID,GOOD_ID)
);
CREATE TABLE ORDERS
(
	ORDER_ID INT PRIMARY KEY NOT NULL,
	SHOP_ID INT NOT NULL
);
CREATE TABLE ORDER_LIST
(
	ORDER_ID INT NOT NULL,
	GOOD_ID INT NOT NULL,
	QUANTITY INT NOT NULL,
	PRIMARY KEY(ORDER_ID,GOOD_ID)
);
CREATE TABLE TASKS
(
	TASK_ID INT NOT NULL PRIMARY KEY,
	WH_ID INT NOT NULL,
	DRIVER_ID INT NULL
);
CREATE TABLE TASKS_GOODS
(
	TASK_ID INT NOT NULL,
	SHOP_ID INT NOT NULL,
	GOOD_ID INT NOT NULL,
	QUANTITY INT NOT NULL,
	PRIMARY KEY(TASK_ID,SHOP_ID,GOOD_ID)
);
CREATE TABLE DRIVERS_HAVE
(
	DRIVER_ID INT NOT NULL,
	GOOD_ID INT NOT NULL,
	QUANTITY INT NOT NULL,
	PRIMARY KEY(DRIVER_ID,GOOD_ID)
);
CREATE TABLE REPORTS
(
	TASK_ID INT PRIMARY KEY,
	SUMTIME INT,
	LENG INT,
	NOTES TEXT
);